# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import energy_pb2 as energy__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in energy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnergyOrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamResiliencePipeline = channel.stream_stream(
                '/energy_resilience.EnergyOrchestrator/StreamResiliencePipeline',
                request_serializer=energy__pb2.AlertSignal.SerializeToString,
                response_deserializer=energy__pb2.SimulationResult.FromString,
                _registered_method=True)


class EnergyOrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamResiliencePipeline(self, request_iterator, context):
        """Bidirectional streaming RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnergyOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamResiliencePipeline': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamResiliencePipeline,
                    request_deserializer=energy__pb2.AlertSignal.FromString,
                    response_serializer=energy__pb2.SimulationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'energy_resilience.EnergyOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('energy_resilience.EnergyOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnergyOrchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamResiliencePipeline(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/energy_resilience.EnergyOrchestrator/StreamResiliencePipeline',
            energy__pb2.AlertSignal.SerializeToString,
            energy__pb2.SimulationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
